### ISSUE TITLE
"SCOPE" cannot be inferenced. 

### ISSUE THREAD

**Issue by wanghangege** [byzhaoAI/BM2CP#7]
"SCOPE" cannot be inferenced. This may be related to the fact that it is a time series sample. Can you update the inference scripts related to "SCOPE" to make the code repository easier to use?

**Comment by wanghangege** [comment]
Traceback (most recent call last):
  File "/home/**/BM2CP/opencood/tools/inference.py", line 293, in <module>
    main()
  File "/home/**/BM2CP/opencood/tools/inference.py", line 129, in main
    pred_box_tensor, pred_score, gt_box_tensor = inference_utils.inference_intermediate_fusion(batch_data, model, opencood_dataset)
  File "/home/**/BM2CP/opencood/tools/inference_utils.py", line 160, in inference_intermediate_fusion
    return inference_early_fusion(batch_data, model, dataset)
  File "/home/**/BM2CP/opencood/tools/inference_utils.py", line 106, in inference_early_fusion
    cav_content = batch_data['ego']  # batch_data['ego']
TypeError: list indices must be integers or slices, not str
